"""SkillTool 常量定义"""

SKILL_TOOL_NAME = "Skill"

# 技能目录
SKILLS_DIRECTORY_NAME = "skills"
SKILL_FILE_NAME = "SKILL.md"

# 错误码
ERROR_CODE_PARSE_ERROR = 1
ERROR_CODE_SKILL_NOT_FOUND = 2
ERROR_CODE_DISABLED = 4
ERROR_CODE_NOT_PROMPT_SKILL = 5
